### ISSUE TITLE
Support for very basic archives

### ISSUE THREAD

**Issue by niconoe** [BelgianBiodiversityPlatform/python-dwca-reader#47]
I.e a simple CSV with column headers.

This was mentioned by Peter and Stijn in the context of their dwca validator. This looks definitely doable. Next question is: is that in the scope of python-dwca-reader.

If not and we don't want to clutter this package with such code, it may be a good idea to implement a higher-level wrapper to abstract things, in a way similar to:

    if given_file_type == dwca:
        dispatch to python-dwca-reader()
    elif given_file_type==csv:
        analyze_headers()
        parse_as_csv()

**Comment by niconoe** [comment]
Would the description of simple darwincore (http://rs.tdwg.org/dwc/terms/simple/index.htm) match this?

**Comment by peterdesmet** [comment]
Haven't read the definition of Simple DwC in depth again, but from what I recall, that would indeed be what we want to support.

**Comment by niconoe** [comment]
Cool! There are also interesting explanations about "darwin core archives without metafile" on page 6 of http://www.gbif.org/resource/80639. 

That looks also similar, so this issue looks like  a duplicate of #7.

**Comment by niconoe** [comment]
@peterdesmet I'm working on this, so that should be there for next release!

**Comment by niconoe** [comment]
Fixed in current!
