### ISSUE TITLE
API inconsistency naming: DwCAReader.get_row_by_index() but CSVDataFile.get_row_by_position()

### ISSUE THREAD

**Issue by niconoe** [BelgianBiodiversityPlatform/python-dwca-reader#69]
!! When updating, also think of the docstrings, documentation, ...

**Comment by niconoe** [comment]
Fixed.

**Comment by abubelinha** [comment]
I am a bit confused with the documentation. I was going to ask about differences between the docs and the examples.  
Perhaps there are two versions of the api, and the docs still contain examples of an old version?

i.e. dwca.core_file_location() vs dwca.descriptor.core.file_location

[API docs](https://python-dwca-reader.readthedocs.io/en/latest/api.html#dwca.read.DwCAReader.core_file_location): _dwca.core_file_location_ 

[Pandas tutorial](https://python-dwca-reader.readthedocs.io/en/latest/pandas_tutorial.html):  _dwca.descriptor.core.file_location_
```Python
with DwCAReader('gbif-results.zip') as dwca:
   print("Core data file is: {}".format(dwca.descriptor.core.file_location)) # => 'occurrence.txt'
```

Thanks
@abubelinha
