### ISSUE TITLE
Any extension of this library for transforming the dwca to sql?

### ISSUE THREAD

**Issue by javierseixas** [BelgianBiodiversityPlatform/python-dwca-reader#77]
I'm looking for a tool for inserting DWCA to SQL. I've seen that this library only reads, and of course, it is possible to code an algorithm for creating sql sentences. However, before develop something like this, I wonder is someone knows any existence library for doing that.

I found a (dwca2sql)[https://github.com/Canadensys/dwca2sql], it looks like a bit outdated.

I appreciate any help! Regards!

**Comment by niconoe** [comment]
You're right @javierseixas : python-dwca-reader only focus on reading. I think it would be a great building block to create what you want, but as far as I know it doesn't exists yet, and the Canadensys is probably outdated.

I'm pretty sure a good/up-to-date dwca-to-sql would be useful to other people in the community. Would you consider also making your project open-source? Do you plan to support multiple target databases (maybe using something like SQLAlchemy? Don't hesitate to keep in touch and ask any question or missing feature you'll have about python-dwca-reader!

**Comment by javierseixas** [comment]
Hi @niconoe ! I'm going to considerer create dwc-to-sql, it wasn't in plans though.
In any case, if I code that, it will be opensource, and probably in python for using python-dwca-reader as library.

Could you recommend me any good documentation to see all python-dwca-reader export escenarios?

**Comment by niconoe** [comment]
I simply wanted something in Python. Also, if I remember correctly, at the time dwca-io had not very active developments, and suffered from limitations I didn't like (for example the supported Darwin Core terms were hard coded in the library, if I'm not mistaken).

Could you give me an example of what documentation you'd need for the "export scenarios" mentioned earlier?

About your dwca-to-sql project, please note that my colleague @andrejjh would also like to implement (probably later in the year, not confirmed yet) a tool to convert Darwin Core Archives to [Tabular Data Packages](https://frictionlessdata.io/docs/tabular-data-package/) (from the frictionless data project). Those data packages can be automatically loaded to a SQL database. So if all goes well, that could also help solve your problem.

**Comment by javierseixas** [comment]
I get your reasons.

By scenarios I meant some output examples of the library, so this is the output it should be converted to sql.

However, I would prefer to work with Java, since the application I'm building is projected in that language and I have more experience with it. So, first I want to check dwca-io. If it doesn't fill my needs, I will reconsider work with python-dwca-reader.

Thanks for your support!

**Comment by abubelinha** [comment]
Hi @javierseixas and @niconoe 

Almost two years later, do you know of any ready made sowtware for DwCA to MySQL conversion?

Thanks

**Comment by andrejjh** [comment]
Hi @abubelinha,

Not sure to understand want you mean by DwCA to MySQL, but last year I wrote a DwCA to Frictionless Data converter tool. Once in Frictionless format its trivial to export to SQL.
see [FrictionlessDarwinCore](https://github.com/frictionlessdata/FrictionlessDarwinCore) tool
on github and [working with SQL](https://frictionlessdata.io/tooling/python/working-with-sql/#reading-from-sql) on FrictionlessData website.
My2cents,

**Comment by abubelinha** [comment]
I don't know what the issue creator meant by DwCA to MySQL.
My understanding is he asked for a ready-made Python script, capable of doing somthing like this:
- Open DwCA zip file and parse its meta.xml to generate a SQL table definition.
- Then parse the data txt file and upload data to that table. I suppose this step could be done with many `INSERT` sentences (either on sentence per file row, or grouping and inserting several rows per sentence). But for huge files perhaps a single `LOAD DATA INFILE` sentence would be much better.

I haven't heard about Frictionless format before, but I will take a look at your links. Thanks @andrejjh
